name: PR Checklist

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions: {}

jobs:
  check-pr-template:
    name: Check PR template
    uses: beeware/.github/.github/workflows/pr-checklist.yml@43aab4a46c7db630ef1bfe817c120677ffa5548e  # main
