name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:

defaults:
  run:
    shell: bash # https://github.com/beeware/briefcase/pull/912

jobs:
  verify-apps:
    name: Build apps
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11"]
        framework: ["toga", "pyside2", "pyside6", "ppb"]
        include:
          - platform: macos-12
            briefcase-data-dir: ~/Library/Caches/org.beeware.briefcase
            pip-cache-dir: ~/Library/Caches/pip
            docker-cache-dir: ~/Library/Containers/com.docker.docker/Data/vms/0/

        exclude:
          # PySide2 doesn't publish a binary wheel that is compatible
          # with Python 3.11, and is unlikely to ever do so.
          - python_version: "3.11"
            framework: "pyside2"

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Cache Briefcase tools
        uses: actions/cache@v3.0.11
        with:
          key: briefcase-${{ matrix.platform }}-${{ matrix.python_version }}
          path: |
            ~/.cookiecutters
            ${{ matrix.briefcase-data-dir }}
            ${{ matrix.pip-cache-dir }}
            ${{ matrix.docker-cache-dir }}
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install packages
        run: pip install briefcase
      - name: Build Xcode project
        run: |
          cd tests/apps/verify-${{ matrix.framework }}
          briefcase create macOS Xcode
          briefcase build macOS Xcode
          briefcase package macOS Xcode --adhoc-sign
      - uses: actions/upload-artifact@v3
        name: Upload failure
        if: failure()
        with:
          name: build-failure-logs-${{ matrix.framework }}
          path: tests/apps/verify-${{ matrix.framework }}/logs/*
